# Generated by Django 4.1 on 2022-09-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=10)),
                ('plan', models.TextField()),
                ('start_data', models.DateTimeField(auto_now_add=True)),
                ('end_data', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
