# Generated by Django 4.1 on 2022-09-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=10)),
                ('plan', models.TextField()),
                ('start_data', models.DateTimeField()),
                ('end_data', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Travels',
        ),
    ]
