# Generated by Django 3.2.7 on 2022-10-13 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_followins'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='followins',
            new_name='followings',
        ),
    ]
